[workspace]
members = ["flavors/*","kaon", "kaon-autocomplete", "kaon-macros", "kwark", "kwark-buffer", "kwark-input"]
resolver = "3"

[workspace.package]
version = "0.0.0"
edition = "2024"
license = "MIT"

[workspace.dependencies]
kaon = { version = "0.0.0", path = "./kaon" }

kwark-buffer = { version = "0.0.0", path = "./kwark-buffer" }
kwark-input = { version = "0.0.0", path = "./kwark-input" }

# Error Handling
thiserror = "2.0.18"
anyhow = "1.0.102"

# Terminal Rendering
crossterm = { version = "0.29.0", features = ["event-stream"] }
ratatui = "0.30.2"
